import type {Lang} from './i18n';
export type SystemId = 'skeletal'|'muscular'|'arterial'|'venous'|'nervous'|'digestive'|'respiratory'|'urinary'|'reproductive'|'lymphatic'|'endocrine'|'integumentary'|'connective'|'sensory'|'cardiac';
type Bi={pl:string;en:string};
export const SYSTEMS: {id:SystemId;name:Bi;color:string;description:Bi}[] = [
 {id:'skeletal',name:{pl:'Szkielet',en:'Skeleton'},color:'#7c5cff',description:{pl:'Kości tworzą podporową ramę ciała, chronią narządy i stanowią punkty przyczepu mięśni. Ich tkanka wewnętrzna magazynuje również minerały i produkuje komórki krwi.',en:'Bones form the supporting framework of the body, protect organs, and provide attachment points for muscles. Their internal tissue also stores minerals and produces blood cells.'}},
 {id:'muscular',name:{pl:'Mięśnie',en:'Muscles'},color:'#e14d8a',description:{pl:'Mięśnie szkieletowe wprawiają ciało w ruch, pociągając za swoje przyczepy. Wraz ze ścięgnami poruszają stawami, stabilizują postawę i wytwarzają ciepło.',en:'Skeletal muscles generate movement by pulling on their attachments. Together with tendons, they move joints, stabilize posture, and produce heat.'}},
 {id:'cardiac',name:{pl:'Serce',en:'Heart'},color:'#ff4d6d',description:{pl:'Serce to mięśniowa pompa z czterema jamami. Jego zastawki kierują krew do przodu przez krążenie płucne i ustrojowe.',en:'The heart is a muscular pump with four chambers. Its valves direct blood forward through the pulmonary and systemic circuits.'}},
 {id:'sensory',name:{pl:'Narządy zmysłów',en:'Sensory organs'},color:'#3ec6ff',description:{pl:'Te struktury odpowiadają za zmysły specjalne, m.in. wzrok, słuch i równowagę. Ich wyspecjalizowane tkanki odbierają bodźce i współpracują z układem nerwowym, przekazując informacje.',en:'These structures contribute to special senses, including sight, hearing, and balance. Their specialized tissues detect stimuli and work with the nervous system to convey information.'}},
 {id:'arterial',name:{pl:'Tętnice',en:'Arteries'},color:'#ff7a45',description:{pl:'Serce napędza krążenie krwi. Tętnice odprowadzają krew z serca do tkanek, a w krążeniu płucnym — do płuc.',en:'The heart drives blood through the circulation. Arteries carry blood away from the heart to supply tissues or, in the pulmonary circuit, to the lungs.'}},
 {id:'venous',name:{pl:'Żyły',en:'Veins'},color:'#2f9e8f',description:{pl:'Żyły odprowadzają krew z powrotem do serca. Sieci powierzchowne i głębokie zbierają krew z tkanek; żyły płucne przywożą krew utlenowaną z płuc.',en:'Veins return blood toward the heart. Superficial and deep networks collect blood from the tissues; the pulmonary veins bring oxygenated blood back from the lungs.'}},
 {id:'nervous',name:{pl:'Układ nerwowy',en:'Nervous system'},color:'#ffb020',description:{pl:'Mózg, rdzeń kręgowy i nerwy obwodowe przekazują i przetwarzają sygnały. Odpowiadają za czucie, ruch, koordynację i automatyczną regulację funkcji organizmu.',en:'The brain, spinal cord, and peripheral nerves carry and process signals. They support sensation, movement, coordination, and automatic regulation of body functions.'}},
 {id:'respiratory',name:{pl:'Układ oddechowy',en:'Respiratory'},color:'#6ea8fe',description:{pl:'Drogi oddechowe prowadzą powietrze do płuc, gdzie tlen i dwutlenek węgla przenikają między powietrzem a krwią. Oddychanie zależy od zmian ciśnienia wytwarzanych przez mięśnie oddechowe.',en:'The airways conduct air to the lungs, where oxygen and carbon dioxide move between air and blood. Breathing depends on pressure changes produced by respiratory muscles.'}},
 {id:'digestive',name:{pl:'Układ trawienny',en:'Digestive'},color:'#d9a441',description:{pl:'Przewód pokarmowy rozkłada pokarm, wchłania składniki odżywcze i wodę oraz przesuwa resztki dalej. Narządy dodatkowe dostarczają żółć i enzymy trawienne.',en:'The digestive tract breaks down food, absorbs nutrients and water, and moves waste onward. Accessory organs contribute bile and digestive enzymes.'}},
 {id:'urinary',name:{pl:'Układ moczowy',en:'Urinary'},color:'#9d7bd8',description:{pl:'Nerki filtrują krew i regulują gospodarkę wodno-elektrolitową oraz równowagę kwasowo-zasadową. Mocz wędruje moczowodami do pęcherza i opuszcza ciało przez cewkę moczową.',en:'The kidneys filter blood and regulate fluid, electrolyte, and acid–base balance. Urine travels through the ureters to the bladder and exits through the urethra.'}},
 {id:'lymphatic',name:{pl:'Układ chłonny',en:'Lymphatic'},color:'#4fc3a1',description:{pl:'Naczynia chłonne zawracają nadmiar płynu tkankowego do krążenia. Węzły chłonne i inne narządy limfatyczne wspierają nadzór i reakcje odpornościowe.',en:'Lymphatic vessels return excess tissue fluid to the circulation. Lymph nodes and other lymphoid organs support immune surveillance and responses.'}},
 {id:'endocrine',name:{pl:'Układ hormonalny',en:'Endocrine'},color:'#f06eaa',description:{pl:'Narządy dokrewne uwalniają hormony do krwi, koordynując procesy takie jak metabolizm, wzrost, reakcje na stres i rozrodczość.',en:'Endocrine organs release hormones into the blood to coordinate processes such as metabolism, growth, stress responses, and reproduction.'}},
 {id:'reproductive',name:{pl:'Układ rozrodczy',en:'Reproductive'},color:'#c96f5e',description:{pl:'Przedstawione tu męskie struktury rozrodcze uczestniczą w produkcji, dojrzewaniu i transporcie plemników oraz w wytwarzaniu hormonów płciowych.',en:'The male reproductive structures represented here contribute to sperm production, maturation, transport, and the production of sex hormones.'}},
 {id:'integumentary',name:{pl:'Powierzchnia ciała',en:'Body surface'},color:'#8d99ae',description:{pl:'Powierzchnia ciała stanowi zewnętrzny punkt odniesienia anatomicznego. Układ powłokowy tworzy barierę ochronną i uczestniczy w czuciu oraz termoregulacji.',en:'The body surface provides an outer anatomical reference. The integumentary system forms a protective barrier and contributes to sensation and temperature regulation.'}},
 {id:'connective',name:{pl:'Tkanka łączna',en:'Connective tissue'},color:'#63b3a0',description:{pl:'Chrząstki, więzadła i inne tkanki łączne podpierają, łączą i oddzielają struktury ciała. Stabilizują stawy i przenoszą obciążenia mechaniczne.',en:'Cartilage, ligaments, and other connective tissues support, connect, and separate structures. Their roles include stabilizing joints and distributing mechanical loads.'}},
];
export interface Part {id:string;name:string;conceptId:string;system:SystemId;chunk:number;positions:number;normals:number;indices:number;vertexCount:number;indexCount:number;bounds:[number[],number[]]}
export interface Concept {id:string;name:string;elements:string[]}
export interface Atlas {version:string;sex?:'male';source?:string;scope?:string;parts:Part[];concepts:Concept[];chunks:{url:string;bytes:number;gzip?:string;gzipBytes?:number}[];triangles:number}
export type View = 'three-quarter'|'front'|'back'|'side';
export interface SceneState {inspectorOpen?:boolean;explode:number;visible:SystemId[];selected:string[];isolate:boolean;view:View;rotate:boolean;reset:number;xray?:boolean;spin?:boolean;glow?:boolean;labels?:boolean;hq?:boolean;region?:Region;zoomSeq?:{dir:1|-1;id:number}|null;regionSeq?:{id:number}|null;lighting?:{exposure:number;key:number;rim:number;ambient:number}}
export const DEFAULT_VISIBLE:SystemId[] = ['cardiac','sensory','skeletal','muscular','arterial','venous','nervous','respiratory','digestive','urinary','lymphatic','endocrine','reproductive','connective'];
// Polish explanations are the source of truth; English mirrors them for the EN toggle.
export const EXPLANATIONS:Record<string,{pl:string;en:string}> = {
 'heart':{pl:'Mięśniowa pompa w klatce piersiowej. Prawa strona wysyła krew do płuc; lewa strona rozprowadza krew w krążeniu ustrojowym.',en:'A muscular pump in the chest. Its right side sends blood to the lungs; its left side sends blood through the systemic circulation.'},
 'liver':{pl:'Duży narząd pod prawą stroną przepony. Przetwarza wchłonięte składniki odżywcze, wytwarza żółć i syntetyzuje wiele białek krwi.',en:'A large organ beneath the right side of the diaphragm. It processes absorbed nutrients, produces bile, and synthesizes many proteins carried in the blood.'},
 'brain':{pl:'Centralny narząd układu nerwowego. Współpracujące ze sobą regiony odpowiadają za percepcję, ruch, pamięć, mowę i regulację funkcji organizmu.',en:'The central organ of the nervous system. Its interconnected regions support perception, movement, memory, language, and the regulation of bodily functions.'},
 'stomach':{pl:'Mięśniowa komora między przełykiem a jelitem cienkim. Magazynuje i miesza pokarm z kwasem oraz enzymami, po czym uwalnia go do dwunastnicy.',en:'A muscular chamber between the esophagus and small intestine. It stores and mixes food with acid and enzymes before releasing it into the duodenum.'},
 'spleen':{pl:'Narząd limfatyczny w lewym górnym obszarze brzucha. Filtruje krew, usuwa stare krwinki i uczestniczy w reakcjach odpornościowych.',en:'A lymphoid organ in the upper left abdomen. It filters blood, removes aging blood cells, and participates in immune responses.'},
 'pancreas':{pl:'Narząd brzuszny o podwójnej roli: trawiennej i hormonalnej. Dostarcza enzymy do jelita cienkiego i uwalnia hormony, m.in. insulinę i glukagon.',en:'An abdominal organ with digestive and endocrine roles. It supplies enzymes to the small intestine and releases hormones including insulin and glucagon.'},
 'urinary bladder':{pl:'Mięśniowy zbiornik w miednicy, który magazynuje mocz dopływający z nerek przez moczowody.',en:'A muscular reservoir in the pelvis that stores urine arriving from the kidneys through the ureters.'},
 'trachea':{pl:'Główna droga oddechowa łącząca krtań z oskrzelami. Chrząstki utrzymują ją otwartą podczas oddychania.',en:'The main airway connecting the larynx to the bronchi. Its cartilage supports keep the airway open during breathing.'},
 'diaphragm':{pl:'Szeroki mięsień oddzielający klatkę piersiową od brzucha. Przy kurczeniu zwiększa objętość klatki i pomaga nabrać powietrza do płuc.',en:'A broad muscle separating the chest and abdomen. When it contracts, it increases chest volume and helps draw air into the lungs.'},
 'lung':{pl:'Parzysty narząd oddechowy. W pęcherzykach płucnych tlen przenika do krwi, a dwutlenek węgla opuszcza ją przy wydechu.',en:'A paired respiratory organ. In the alveoli, oxygen passes into the blood while carbon dioxide leaves it with each exhale.'},
 'kidney':{pl:'Parzysty narząd położony zaotrzewkowo, filtrujący krew. Produkuje mocz, reguluje ciśnienie i gospodarkę wodno-elektrolitową.',en:'A paired retroperitoneal organ that filters blood. It produces urine and regulates blood pressure and fluid balance.'},
 'esophagus':{pl:'Mięśniowy przewód łączący gardło z żołądkiem. Skurcze perystaltyczne przesuwają pokarm w dół.',en:'A muscular tube connecting the pharynx to the stomach. Peristaltic waves move food downward.'},
 'gallbladder':{pl:'Mały woreczek pod wątrobą. Magazynuje i zagęszcza żółć, którą uwalnia do dwunastnicy po posiłku.',en:'A small sac beneath the liver. It stores and concentrates bile, releasing it into the duodenum after meals.'},
 'femur':{pl:'Najdłuższa i najsilniejsza kość ciała. Łączy biodro z kolanem i przenosi ciężar ciała podczas chodzenia.',en:'The longest and strongest bone in the body. It links hip to knee and carries body weight when walking.'},
};
// Curated organ gallery: Polish names with descriptions for the "Organy" panel.
export const ORGANS:{en:string;pl:string}[] = [
 {en:'heart',pl:'Serce'},{en:'lung',pl:'Płuca'},{en:'brain',pl:'Mózg'},
 {en:'liver',pl:'Wątroba'},{en:'stomach',pl:'Żołądek'},{en:'spleen',pl:'Śledziona'},
 {en:'pancreas',pl:'Trzustka'},{en:'kidney',pl:'Nerka'},{en:'urinary bladder',pl:'Pęcherz moczowy'},
 {en:'gallbladder',pl:'Pęcherzyk żółciowy'},{en:'esophagus',pl:'Przełyk'},{en:'trachea',pl:'Tchawica'},
 {en:'diaphragm',pl:'Przepona'},{en:'femur',pl:'Kość udowa'},
];
export type Region='all'|'head'|'chest'|'abdomen'|'pelvis'|'limbs';
export const REGIONS:{id:Region;pl:string;en:string}[] = [
 {id:'all',pl:'Całe ciało',en:'Whole body'},{id:'head',pl:'Głowa',en:'Head'},
 {id:'chest',pl:'Klatka piersiowa',en:'Chest'},{id:'abdomen',pl:'Brzuch',en:'Abdomen'},
 {id:'pelvis',pl:'Miednica',en:'Pelvis'},{id:'limbs',pl:'Kończyny',en:'Limbs'},
];
// Approximate body-region bands on the normalized vertical axis (0 = feet, 1 = top of head).
export function regionOf(centerY:number,minY:number,maxY:number):Region{
 const yn=(centerY-minY)/Math.max(1e-6,maxY-minY);
 if(yn>=.86)return 'head';if(yn>=.70)return 'chest';if(yn>=.55)return 'abdomen';if(yn>=.44)return 'pelvis';return 'limbs';
}
export function explanation(name:string,system:SystemId,lang:Lang){const e=EXPLANATIONS[name.toLowerCase()];return (e?e[lang]:undefined) ?? SYSTEMS.find(s=>s.id===system)?.description[lang] ?? '';}
// Structure names come from BodyParts3D (English/Latin nomenclature) and are shared by both languages.
